### ISSUE TITLE
Crashing - Android 6 - MI Phone

### ISSUE THREAD

**Issue by sah-anshu** [lvamsavarthan/Hify#12]
`12-16 18:29:21.891 16761-16761/? W/subsystem_ramdu: type=1400 audit(0.0:552761): avc: denied { read } for name="/" dev="tmpfs" ino=11107 scontext=u:r:subsystem_ramdump:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=0
12-16 18:29:21.908 16761-16761/? E/subsystem_ramdump: Unable to open /dev
12-16 18:29:21.908 16761-16761/? E/subsystem_ramdump: Failed to find pil ramdump
12-16 18:29:22.071 1450-1512/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{739c6f6 u0 com.miui.home/.launcher.Launcher t160} time:70417291
12-16 18:29:22.073 1450-1512/? I/Timeline: Timeline: App_transition_stopped time:70417293
12-16 18:29:22.803 1450-4575/? W/ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null. 
12-16 18:29:23.574 863-863/? I/MSM-irqbalance: Decided to move IRQ177 from CPU2 to CPU0
12-16 18:29:23.921 1450-3917/? W/ActivityManager: cann't getContentProviderImpl: gmail-ofls, cpi is null. 
12-16 18:29:23.923 3490-28857/? I/Icing: Indexing com.google.android.gm-internal.3p:EmailMessage from com.google.android.gm
12-16 18:29:24.043 3490-28857/? I/Icing: Indexing done com.google.android.gm-internal.3p:EmailMessage
12-16 18:29:24.060 1450-5072/? W/ErrorReport: Fail to sendHttpRequest
    java.lang.IllegalArgumentException: HTTP entity may not be null
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:115)
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:151)
        at miui.util.ErrorReport.c(SourceFile:396)
        at miui.util.ErrorReport.sendReportRequest(SourceFile:353)
        at miui.util.ErrorReport$1.a(SourceFile:369)
        at miui.util.ErrorReport$1.doInBackground(SourceFile:366)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
12-16 18:29:24.061 1450-5072/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1295 android.content.ContextWrapper.bindService:614 miui.os.DropBoxManager.cG:361 miui.os.DropBoxManager.a:350 miui.os.DropBoxManager.addText:314 
12-16 18:29:24.299 4580-4749/? I/octvm_klo: gathering logcat log done
12-16 18:29:24.299 4580-4749/? I/octvm_klo: klo unlock
12-16 18:29:24.792 5922-5922/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
12-16 18:29:24.801 5922-5922/? D/wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=212992 outq=0 send_len=48
12-16 18:29:25.076 3490-28857/? I/Icing: Indexing com.google.android.gm-internal.3p:EmailMessage from com.google.android.gm

`

Thanks in Advance.

**Comment by lvamsavarthan** [comment]
Uninstall the app, clear phone cache, and try installing again
